name: 'Wechat Work Robot Message'
description: 'wechat work robot message for github action'
author: 'sliu@hipacloud.com'
inputs:
  url:
    description: 'wechat work robot webhook'
    required: true

  type:
    description: 'message type'
    default: 'text'

  content:
    description: 'message content'
    required: true

  at:
    description: 'at users'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "message-square"